# Ejemplo de ejecucion para enviar las variables: MY_UID="$(id -u)" MY_GID="$(id -g)" docker-compose up

version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    #user: ${MY_UID}:${MY_GID} #https://stackoverflow.com/questions/64857370/using-current-user-when-running-container-in-docker-compose
    volumes:
      # - postgres-db:/var/lib/postgresql/data      
      #- /etc/passwd:/etc/passwd:ro #https://github.com/docker-library/docs/tree/8c1890611e4165defb793d3fe0653c65c1fb9b1b/postgres#arbitrary---user-notes
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      #- PGDATA=/var/lib/postgresql/data/pgdata

#https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#mapped-files-and-directories
#sudo chown -R 5050:5050 <host_directory>  
  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

# volumes:
#   postgres-db:
#     external: true

#sudo chmod -R 775 pgadmin
#sudo chmod -R 775 postgres


