#https://kubernetes.io/es/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  #echo -n 'superman@goo.com' | base64
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vLmNvbQ==
  #echo -n 'EstoEsUnPassWordSecreto' | base64
  DB_PASSWORD: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=