#https://kubernetes.io/es/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  #echo -n 'postgres' | base64
  DB_USER: cG9zdGdyZXM=
  #echo -n 'EstoEsUnPassWordSecreto' | base64
  DB_PASSWORD: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8=